api:
  host: "0.0.0.0"
  port: 8000
  api_key: "test-api-key"
  key: "test-api-key"
  log_level: "info"
  detailed_errors: true
  allow_origins:
    - "http://localhost:3000"
    - "http://localhost:3001"
    - "http://127.0.0.1:3000"
    - "http://127.0.0.1:3001"
  version: "0.1.0"

security:
  api_keys:
    - "test_api_key"
    - "test-api-key"

database:
  type: "sqlite"
  url: "sqlite:///profiler.db"
  pool_size: 20
  max_overflow: 10
  echo: false

services:
  qa:
    prompt_template_path: "app/backend/services/qa_service/templates"
    temperature: 0.7
    max_tokens: 1000
    system_prompt: "You are a helpful assistant that helps students build their profiles."
  
  document:
    upload_dir: "uploads"
    allowed_extensions:
      - ".pdf"
      - ".doc"
      - ".docx"
      - ".txt"
    max_file_size_mb: 10
    
  recommendation:
    storage_type: "chroma"
    chroma_dir: "chroma_db"
    collection_name: "recommendations"
    quality_threshold: 0.7
    min_section_quality: 0.5
    
ai_clients:
  deepseek:
    api_key: "test-api-key"
    model: "deepseek-ai/deepseek-v3"
    url: "https://api.deepseek.ai/v1"
    timeout: 60
    
external_services:
  kevin:
    enabled: true
    base_url: "http://localhost:5000" 
    api_key: "test-api-key"
    timeout_seconds: 5
    retry_attempts: 3
