# Student Profiler Backend Configuration

# API Settings
api:
  host: "0.0.0.0"
  port: 8000
  debug: false
  api_key: "test_key"  # API key for testing
  timeout: 60  # seconds
  rate_limit:
    window_seconds: 60
    max_requests: 100
    enabled: true

# AI Clients
ai_clients:
  deepseek:
    url: "https://api.deepseek.com/v1"
    api_key: "sk-a8c90a7a82884c0e994508e0608728eb"  # Set this via environment variable
    model: "r1-alpha"
    batch_size: 5
    max_tokens: 2000
    temperature: 0.7
    timeout: 30  # seconds
    retry:
      max_attempts: 3
      backoff_factor: 2

# Database Settings
database:
  chromadb:
    host: "localhost"
    port: 8001
    path: "./data/chroma"
    collections:
      profiles:
        name: "profiles"
        embedding_function: "sentence-transformers/all-MiniLM-L6-v2"
        distance_metric: "cosine"
      recommendations:
        name: "recommendations"
        embedding_function: "sentence-transformers/all-MiniLM-L6-v2"
        distance_metric: "cosine"

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/profiler.log"
  rotation: 
    max_bytes: 10485760  # 10MB
    backup_count: 5

# Document Analysis
documents:
  allowed_types:
    - "pdf"
    - "docx"
    - "txt"
  max_size_mb: 10
  extract_tool: "local"  # "local" or "api"

# Profile Workflow
workflow:
  sections:
    - name: "academic"
      required: true
      min_quality_score: 0.7
    - name: "extracurricular"
      required: true
      min_quality_score: 0.6
    - name: "personal"
      required: true
      min_quality_score: 0.6
    - name: "essays"
      required: false
      min_quality_score: 0.8
  max_iterations_per_section: 5
  human_review_quality_threshold: 0.5

# WebSocket
websocket:
  ping_interval: 30  # seconds
  ping_timeout: 10  # seconds
  max_message_size: 1048576  # 1MB

# Security
security:
  api_keys:
    - "test_key"
  cors:
    allowed_origins:
      - "http://localhost:3000"
      - "https://profile.example.com"
    allow_credentials: true
  ratelimit:
    ip_window_seconds: 3600  # 1 hour
    ip_max_requests: 1000 