# Configuration for Canadian university website scraping
scraping:
  max_depth: 3
  timeout: 30
  max_pages: 100
  user_agent: random
  max_retries: 3
  retry_delay: 2
  # Add advanced timeout and debugging settings
  max_crawl_duration: 600
  max_url_processing_time: 120
  enable_emergency_exit: true
  enable_verbose_logging: false
  watchdog_interval: 30
  activity_timeout: 180
  # Block patterns for social media and other unwanted domains
  block_patterns:
    - "facebook.com"
    - "twitter.com"
    - "instagram.com"
    - "linkedin.com"
    - "youtube.com"
    - "tiktok.com"
    - "pinterest.com"
    - "reddit.com"
    - "snapchat.com"
  # Problem URL handling
  skip_problematic_urls: true
  problematic_domains:
    - "mcmastercce.ca"
    - "www.mcmastercce.ca"
  ssl_verification: false
  # Scraper agent settings
  headers:
    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
    Accept-Language: "en-US,en;q=0.5"
    Accept-Encoding: "gzip, deflate, br"
    Connection: "keep-alive"
    Upgrade-Insecure-Requests: "1"
  
# Vector database configuration
vector_db:
  collection_name: "canadian_universities"
  persist_directory: "./data/vectordb"
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"

# LLM configuration
llm:
  provider: "deepseek"
  api_key: "sk-a8c90a7a82884c0e994508e0608728eb"
  model_name: "deepseek-chat"
  temperature: 0.3
  max_tokens: 1200
  request_timeout: 45
  use_cache: true
  max_retries: 3
  retry_delay: 2
  fallback_to_huggingface: false
  top_p: 0.88
  presence_penalty: 0.1
  frequency_penalty: 0.2

# Web search configuration
web_search:
  enabled: true
  tavily_api_key: "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"
  search_depth: "basic"
  max_results: 3

# Workflow settings
workflow:
  relevance_threshold: 0.6
  hallucination_threshold: 0.7
  include_web_results_in_rag: false

# Logging configuration
logging:
  level: "INFO"
  console_level: "DEBUG"
  file_level: "INFO"
  max_file_size: 10485760
  backup_count: 5
  log_api_calls: true
  log_dir: "./logs"

# University websites to scrape
universities:
  - name: "University of Toronto"
    base_url: "https://www.utoronto.ca/"
    focus_urls:
      - "https://future.utoronto.ca/finances/fees/"
      - "https://future.utoronto.ca/finances/"
      - "https://future.utoronto.ca/finances/financial-aid/"
      - "https://future.utoronto.ca/finances/awards/"
      - "https://planningandbudget.utoronto.ca/tuition-fee-schedules/"
      - "https://studentaccount.utoronto.ca/tuition-fees/current-academic-year-fees/"
      - "https://studentaccount.utoronto.ca/tuition-fees/fee-payment-service-charge-billing-deadlines/"
      - "https://www.utoronto.ca/academics/international-student-fees"
      - "https://www.utoronto.ca/academics/domestic-student-fees"
  
  - name: "McMaster University"
    base_url: "https://www.mcmaster.ca/"
    focus_urls:
      - "https://www.mcmaster.ca/academics/"
      - "https://future.mcmaster.ca/admissions/"
      - "https://registrar.mcmaster.ca/tuition-fees/"
      - "https://sfas.mcmaster.ca/scholarships/"

  - name: "University of Waterloo"
    base_url: "https://uwaterloo.ca/"
    focus_urls:
      - "https://uwaterloo.ca/future-students/programs"
      - "https://uwaterloo.ca/future-students/admissions"
      - "https://uwaterloo.ca/student-financial-services"
      - "https://uwaterloo.ca/student-awards-financial-aid/"

  - name: "Western University"
    base_url: "https://www.uwo.ca/"
    focus_urls:
      - "https://www.uwo.ca/academics/"
      - "https://welcome.uwo.ca/admissions/"
      - "https://registrar.uwo.ca/student_finances/"
      - "https://registrar.uwo.ca/student_finances/scholarships_awards/"

  - name: "Queen's University"
    base_url: "https://www.queensu.ca/"
    focus_urls:
      - "https://www.queensu.ca/academics/"
      - "https://www.queensu.ca/future-students"
      - "https://www.queensu.ca/registrar/tuition-fees"
      - "https://www.queensu.ca/studentawards/"

  - name: "University of Ottawa"
    base_url: "https://www.uottawa.ca/"
    focus_urls:
      - "https://www.uottawa.ca/academic/en"
      - "https://www.uottawa.ca/undergraduate-admissions/"
      - "https://www.uottawa.ca/university-fees/"
      - "https://www.uottawa.ca/financial-aid-awards/"

  - name: "York University"
    base_url: "https://www.yorku.ca/"
    focus_urls:
      - "https://www.yorku.ca/programs/"
      - "https://www.yorku.ca/admissions/"
      - "https://sfs.yorku.ca/fees/"
      - "https://sfs.yorku.ca/scholarships/"

  - name: "Carleton University"
    base_url: "https://carleton.ca/"
    focus_urls:
      - "https://carleton.ca/academics/"
      - "https://admissions.carleton.ca/"
      - "https://carleton.ca/studentaccounts/tuition-fees/"
      - "https://carleton.ca/awards/"

  # British Columbia Universities
  - name: "University of British Columbia"
    base_url: "https://www.ubc.ca/"
    focus_urls:
      - "https://www.ubc.ca/academics/"
      - "https://you.ubc.ca/applying-ubc/"
      - "https://students.ubc.ca/enrolment/finances/tuition-fees"
      - "https://students.ubc.ca/enrolment/finances/awards-scholarships-bursaries"

  - name: "Simon Fraser University"
    base_url: "https://www.sfu.ca/"
    focus_urls:
      - "https://www.sfu.ca/programs"
      - "https://www.sfu.ca/admission"
      - "https://www.sfu.ca/students/financialaid/costs"
      - "https://www.sfu.ca/students/financialaid/entrance"

  - name: "University of Victoria"
    base_url: "https://www.uvic.ca/"
    focus_urls:
      - "https://www.uvic.ca/undergraduate/programs/"
      - "https://www.uvic.ca/undergraduate/admissions/"
      - "https://www.uvic.ca/registrar/students/financials/"
      - "https://www.uvic.ca/registrar/students/financials/financial-aid/"

  # Quebec Universities
  - name: "McGill University"
    base_url: "https://www.mcgill.ca/"
    focus_urls:
      - "https://www.mcgill.ca/undergraduate-admissions/"
      - "https://www.mcgill.ca/undergraduate-admissions/apply"
      - "https://www.mcgill.ca/student-accounts/tuition-charges"
      - "https://www.mcgill.ca/studentaid/scholarships-aid"

  - name: "Université de Montréal"
    base_url: "https://www.umontreal.ca/"
    focus_urls:
      - "https://admission.umontreal.ca/programmes/"
      - "https://admission.umontreal.ca/admission/"
      - "https://registraire.umontreal.ca/droits-de-scolarite/"
      - "https://bourses.umontreal.ca/"

  - name: "Laval University"
    base_url: "https://www.ulaval.ca/"
    focus_urls:
      - "https://www.ulaval.ca/etudes/programmes"
      - "https://www.ulaval.ca/admission"
      - "https://www.ulaval.ca/etudes/droits-de-scolarite"
      - "https://www.bbaf.ulaval.ca/"

  - name: "Université du Québec"
    base_url: "https://www.uquebec.ca/"
    focus_urls:
      - "https://www.uquebec.ca/reseau/fr/futurs-etudiants/programmes-detudes"
      - "https://www.uquebec.ca/reseau/fr/futurs-etudiants/admission"
      - "https://www.uquebec.ca/reseau/fr/futurs-etudiants/couts-des-etudes"
      - "https://www.uquebec.ca/reseau/fr/futurs-etudiants/bourses"

  # Alberta Universities
  - name: "University of Alberta"
    base_url: "https://www.ualberta.ca/"
    focus_urls:
      - "https://www.ualberta.ca/admissions"
      - "https://www.ualberta.ca/admissions/undergraduate/tuition-and-scholarships"
      - "https://www.ualberta.ca/registrar/scholarships-awards-financial-support"

  - name: "University of Calgary"
    base_url: "https://www.ucalgary.ca/"
    focus_urls:
      - "https://www.ucalgary.ca/future-students/undergraduate/explore-programs"
      - "https://www.ucalgary.ca/future-students/undergraduate/apply"
      - "https://www.ucalgary.ca/registrar/finances/tuition-and-fees"
      - "https://www.ucalgary.ca/registrar/finances/awards-scholarships-and-bursaries"

  # Other Major Universities
  - name: "Dalhousie University"
    base_url: "https://www.dal.ca/"
    focus_urls:
      - "https://www.dal.ca/academics/programs"
      - "https://www.dal.ca/admissions"
      - "https://www.dal.ca/admissions/money_matters/tuition_fees"
      - "https://www.dal.ca/admissions/money_matters/funding-sources/scholarships"

  - name: "University of Saskatchewan"
    base_url: "https://www.usask.ca/"
    focus_urls:
      - "https://programs.usask.ca/"
      - "https://admissions.usask.ca/"
      - "https://students.usask.ca/money/tuition-fees/"
      - "https://students.usask.ca/money/scholarships.php"

  - name: "University of Manitoba"
    base_url: "https://umanitoba.ca/"
    focus_urls:
      - "https://umanitoba.ca/explore/programs-of-study"
      - "https://umanitoba.ca/admissions/"
      - "https://umanitoba.ca/admissions/undergraduate/costs-and-finances"
      - "https://umanitoba.ca/financial-aid-and-awards/"

  # Provincial Application Portals
  - name: "ApplyAlberta"
    base_url: "https://www.applyalberta.ca/"
    focus_urls:
      - "https://www.applyalberta.ca/program-search"
      - "https://www.applyalberta.ca/how-to-apply"
      - "https://www.applyalberta.ca/finance-your-education"

  - name: "EducationPlannerBC"
    base_url: "https://www.educationplannerbc.ca/"
    focus_urls:
      - "https://www.educationplannerbc.ca/search"
      - "https://www.educationplannerbc.ca/plan/apply"
      - "https://www.educationplannerbc.ca/plan/finance"

  - name: "Ontario Universities' Application Centre (OUAC)"
    base_url: "https://www.ouac.on.ca/"
    focus_urls:
      - "https://www.ouac.on.ca/ouac-101/"
      - "https://www.ouac.on.ca/ouac-105/"
      - "https://www.ontariouniversitiesinfo.ca/"

  - name: "SRAM (Quebec)"
    base_url: "https://www.sram.qc.ca/"
    focus_urls:
      - "https://www.sram.qc.ca/diploma-of-college-studies/available-programs"
      - "https://www.sram.qc.ca/diploma-of-college-studies/student-for-a-day"
      - "https://www.sram.qc.ca/international-student/admission"

  - name: "SRACQ (Quebec)"
    base_url: "https://www.sracq.qc.ca/"
    focus_urls:
      - "https://www.sracq.qc.ca/programmes/"
      - "https://www.sracq.qc.ca/admission/"
      - "https://www.sracq.qc.ca/international/" 