version: '3'

services:
  postgres:
    image: postgres:15
    container_name: profiler-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=profiler
    restart: unless-stopped
    networks:
      - profiler-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  profiler-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local 