version: '3'

services:
  ui-mongodb:
    image: mongo:latest
    container_name: kevin-ui-mongodb
    ports:
      - "27018:27017"  # Different port from the main MongoDB to avoid conflicts
    volumes:
      - ./data:/data/db
      - ./config:/etc/mongo
      - ./init/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secure_password
      - MONGO_INITDB_DATABASE=kevindb
    command: --config /etc/mongo/mongod.conf
    restart: unless-stopped
    networks:
      - ui-network

networks:
  ui-network:
    driver: bridge 